import React from 'react';
import {
  FileText,
  Wand2,
  BookOpen,
  Image,
  Eraser,
  Merge,
  FileEdit,
  FileImage,
  FileUp,
  Scaling,
  Shrink,
  Book,
  Scissors,
  FileLock2,
  FileSpreadsheet,
  User,
  CaseSensitive,
  Library,
  FileVideo,
  Wind,
  AudioLines,
  Youtube,
  UserCog,
  FileKey2,
  PenLine,
  QrCode,
  Link,
  RotateCw,
  Timer,
  VolumeX,
  Type,
  Baseline,
  Briefcase,
  Star,
  HelpCircle,
  File,
  FlipHorizontal,
  FileSearch,
  Languages,
  Signature,
  PieChart,
  Palette,
  Eye,
  Settings,
  ShieldCheck,
  Smartphone,
  CheckCircle2,
  Hash,
  Mail,
  List,
  FileCode,
  Music,
  Video,
  Layout,
  Globe,
  Archive,
  Subtitles,
  Mic,
  Clapperboard,
  FileAudio,
  Code2,
  Map,
  History,
  Activity,
  Zap,
  Twitter,
  Instagram,
  Facebook,
  Linkedin,
  Monitor,
  Printer,
  Search,
  MessageSquare,
  Sparkles,
  RefreshCw,
} from 'lucide-react';

export type ToolCategory = 'AI Write' | 'Image Tools' | 'Pdf Tools' | 'Video Tools' | 'Converter Tools' | 'Web Tools' | 'Other Tools';

export type Tool = {
  title: string;
  slug: string;
  description: string;
  href: string;
  category: ToolCategory;
  icon: React.ElementType;
};

function formatTitle(slug: string) {
  return slug
    .split('-')
    .map((word) => {
      const upper = word.toUpperCase();
      if (['PDF', 'JPG', 'PNG', 'SVG', 'HEIC', 'WEBP', 'EPS', 'TIFF', 'AI', 'AZW3', 'MOBI', 'EPUB', 'XLS', 'XLSX', 'CSV', 'JSON', 'XML', 'PPT', 'PPTX', 'DOCX', 'MSG', 'URL', 'AAC', 'MP3', 'MP4', 'M4A', 'WAV', 'OGG', 'MKV', 'AVI', 'MOV', 'FLAC', 'M4R', 'WEBM', 'GIF', 'APNG', 'AVIF', 'NDA', 'FB', 'INST'].includes(upper)) {
        return upper;
      }
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
}

const rawTools: { slug: string; path: string; category: ToolCategory; icon: React.ElementType; priority?: boolean }[] = [
  // --- PRIORITY TOOLS ---
  { slug: "remove-bg", path: "image", category: "Image Tools", icon: Eraser, priority: true },
  { slug: "ai-image-generator", path: "image", category: "Image Tools", icon: Sparkles, priority: true },
  { slug: "cleanup-picture", path: "image", category: "Image Tools", icon: Eraser, priority: true },
  { slug: "upscale", path: "image", category: "Image Tools", icon: Scaling, priority: true },
  { slug: "merge", path: "pdf", category: "Pdf Tools", icon: Merge, priority: true },
  { slug: "edit", path: "pdf", category: "Pdf Tools", icon: FileEdit, priority: true },
  { slug: "compress", path: "pdf", category: "Pdf Tools", icon: Shrink, priority: true },
  { slug: "ai-rephraser", path: "write", category: "AI Write", icon: RefreshCw, priority: true },
  { slug: "grammar-fixer", path: "write", category: "AI Write", icon: CheckCircle2, priority: true },
  { slug: "summarize-youtube", path: "write", category: "AI Write", icon: Youtube, priority: true },
  { slug: "compress", path: "video", category: "Video Tools", icon: Shrink, priority: true },
  { slug: "cutter", path: "video", category: "Video Tools", icon: Scissors, priority: true },

  // --- IMAGE TOOLS ---
  { slug: "add-images", path: "image", category: "Image Tools", icon: Image },
  { slug: "ai-art-generator", path: "image", category: "Image Tools", icon: Palette },
  { slug: "blur-background", path: "image", category: "Image Tools", icon: Eye },
  { slug: "border", path: "image", category: "Image Tools", icon: Layout },
  { slug: "change-bg-photo", path: "image", category: "Image Tools", icon: Image },
  { slug: "chart-maker", path: "image", category: "Image Tools", icon: PieChart },
  { slug: "collage-maker", path: "image", category: "Image Tools", icon: Layout },
  { slug: "colorize-photo", path: "image", category: "Image Tools", icon: Palette },
  { slug: "combine-maker", path: "image", category: "Image Tools", icon: Merge },
  { slug: "compress", path: "image", category: "Image Tools", icon: Shrink },
  { slug: "crop", path: "image", category: "Image Tools", icon: Scissors },
  { slug: "crop-circle", path: "image", category: "Image Tools", icon: Scissors },
  { slug: "eps-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "eps-to-png", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "eps-to-svg", path: "image", category: "Image Tools", icon: FileCode },
  { slug: "flip", path: "image", category: "Image Tools", icon: FlipHorizontal },
  { slug: "font-to-png", path: "image", category: "Image Tools", icon: Type },
  { slug: "gif-to-apng", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "gif-to-avif", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "gif-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "gif-to-png", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "grayscale", path: "image", category: "Image Tools", icon: Palette },
  { slug: "heic-to-avif", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "heic-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "heic-to-png", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "jpg-to-avif", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "jpg-to-gif", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "jpg-to-png", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "jpg-to-svg", path: "image", category: "Image Tools", icon: FileCode },
  { slug: "jpg-to-tiff", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "jpg-to-webp", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "make-background-transparent", path: "image", category: "Image Tools", icon: Eraser },
  { slug: "metadata", path: "image", category: "Image Tools", icon: FileSearch },
  { slug: "pixelate", path: "image", category: "Image Tools", icon: Palette },
  { slug: "png-to-avif", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "png-to-eps", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "png-to-gif", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "png-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "png-to-svg", path: "image", category: "Image Tools", icon: FileCode },
  { slug: "png-to-tiff", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "png-to-webp", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "profile-photo", path: "image", category: "Image Tools", icon: User },
  { slug: "psd-to-ai", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "psd-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "psd-to-pdf", path: "image", category: "Image Tools", icon: FileText },
  { slug: "psd-to-png", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "psd-to-svg", path: "image", category: "Image Tools", icon: FileCode },
  { slug: "remove-objects", path: "image", category: "Image Tools", icon: Eraser },
  { slug: "remove-person", path: "image", category: "Image Tools", icon: Eraser },
  { slug: "remove-text-photo", path: "image", category: "Image Tools", icon: Eraser },
  { slug: "remove-watermark-photo", path: "image", category: "Image Tools", icon: Eraser },
  { slug: "repair-defects", path: "image", category: "Image Tools", icon: Wand2 },
  { slug: "resize", path: "image", category: "Image Tools", icon: Scaling },
  { slug: "sharpen", path: "image", category: "Image Tools", icon: Wand2 },
  { slug: "split", path: "image", category: "Image Tools", icon: Scissors },
  { slug: "svg-to-png", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "text-image-generator", path: "image", category: "Image Tools", icon: Type },
  { slug: "text-to-image", path: "image", category: "Image Tools", icon: Sparkles },
  { slug: "tiff-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "tiff-to-png", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "tiff-to-svg", path: "image", category: "Image Tools", icon: FileCode },
  { slug: "tiff-to-text", path: "image", category: "Image Tools", icon: Type },
  { slug: "to-text", path: "image", category: "Image Tools", icon: Type },
  { slug: "translate", path: "image", category: "Image Tools", icon: Languages },
  { slug: "unblur", path: "image", category: "Image Tools", icon: Eye },
  { slug: "vsd-to-docx", path: "image", category: "Image Tools", icon: FileText },
  { slug: "vsd-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "vsd-to-pdf", path: "image", category: "Image Tools", icon: FileText },
  { slug: "vsd-to-pptx", path: "image", category: "Image Tools", icon: FileVideo },
  { slug: "vsdx-to-docx", path: "image", category: "Image Tools", icon: FileText },
  { slug: "vsdx-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "vsdx-to-pdf", path: "image", category: "Image Tools", icon: FileText },
  { slug: "vsdx-to-pptx", path: "image", category: "Image Tools", icon: FileVideo },
  { slug: "webp-to-avif", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "webp-to-gif", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "webp-to-jpg", path: "image", category: "Image Tools", icon: FileImage },
  { slug: "webp-to-png", path: "image", category: "Image Tools", icon: FileImage },

  // --- AI WRITE ---
  { slug: "ai-detector", path: "write", category: "AI Write", icon: ShieldCheck },
  { slug: "ai-twitter-generator", path: "write", category: "AI Write", icon: Twitter },
  { slug: "article-generator", path: "write", category: "AI Write", icon: PenLine },
  { slug: "article-rewriter", path: "write", category: "AI Write", icon: RotateCw },
  { slug: "article-writer", path: "write", category: "AI Write", icon: PenLine },
  { slug: "bill-sale-generator", path: "write", category: "AI Write", icon: FileText },
  { slug: "blog-outline", path: "write", category: "AI Write", icon: List },
  { slug: "business-name-generator", path: "write", category: "AI Write", icon: Briefcase },
  { slug: "business-plan-generator", path: "write", category: "AI Write", icon: Briefcase },
  { slug: "business-slogan-generator", path: "write", category: "AI Write", icon: Briefcase },
  { slug: "cold-email-writer", path: "write", category: "AI Write", icon: Mail },
  { slug: "content-brief-generator", path: "write", category: "AI Write", icon: List },
  { slug: "content-improver", path: "write", category: "AI Write", icon: Wand2 },
  { slug: "content-planner", path: "write", category: "AI Write", icon: Map },
  { slug: "content-summarizer", path: "write", category: "AI Write", icon: BookOpen },
  { slug: "essay-writer", path: "write", category: "AI Write", icon: PenLine },
  { slug: "explain-like-five", path: "write", category: "AI Write", icon: HelpCircle },
  { slug: "facebook-ad-headlines", path: "write", category: "AI Write", icon: Facebook },
  { slug: "faq-generator", path: "write", category: "AI Write", icon: HelpCircle },
  { slug: "humanizer-ai", path: "write", category: "AI Write", icon: UserCog },
  { slug: "instagram-caption-generator", path: "write", category: "AI Write", icon: Instagram },
  { slug: "instagram-story-ideas", path: "write", category: "AI Write", icon: Instagram },
  { slug: "landing-page-copy", path: "write", category: "AI Write", icon: Layout },
  { slug: "linkedin-post-generator", path: "write", category: "AI Write", icon: Linkedin },
  { slug: "listicle-writer", path: "write", category: "AI Write", icon: List },
  { slug: "meta-description-generator", path: "write", category: "AI Write", icon: Search },
  { slug: "nda-generator", path: "write", category: "AI Write", icon: FileText },
  { slug: "paragraph-completer", path: "write", category: "AI Write", icon: PenLine },
  { slug: "paragraph-rewriter", path: "write", category: "AI Write", icon: RotateCw },
  { slug: "paragraph-writer", path: "write", category: "AI Write", icon: PenLine },
  { slug: "paraphrasing", path: "write", category: "AI Write", icon: RefreshCw },
  { slug: "podcast-writer", path: "write", category: "AI Write", icon: Mic },
  { slug: "poll-generator", path: "write", category: "AI Write", icon: List },
  { slug: "post-generator", path: "write", category: "AI Write", icon: MessageSquare },
  { slug: "post-ideas", path: "write", category: "AI Write", icon: Sparkles },
  { slug: "post-rewriter", path: "write", category: "AI Write", icon: RotateCw },
  { slug: "post-writer", path: "write", category: "AI Write", icon: PenLine },
  { slug: "purchase-agreement-generator", path: "write", category: "AI Write", icon: FileText },
  { slug: "real-estate-description", path: "write", category: "AI Write", icon: Map },
  { slug: "sentence-rewriter", path: "write", category: "AI Write", icon: RotateCw },
  { slug: "shorten-content", path: "write", category: "AI Write", icon: Shrink },
  { slug: "story-generator", path: "write", category: "AI Write", icon: Book },
  { slug: "tiktok-script-writer", path: "write", category: "AI Write", icon: Video },
  { slug: "title-rewriter", path: "write", category: "AI Write", icon: RotateCw },
  { slug: "tone-of-voice", path: "write", category: "AI Write", icon: Mic },
  { slug: "translate", path: "write", category: "AI Write", icon: Languages },
  { slug: "trivia-generator", path: "write", category: "AI Write", icon: HelpCircle },
  { slug: "word-counter", path: "write", category: "AI Write", icon: Hash },
  { slug: "youtube-script-writer", path: "write", category: "AI Write", icon: Youtube },
  { slug: "automation-wizard", path: "content-machine", category: "AI Write", icon: Zap },
  { slug: "bulk-generator", path: "content-machine", category: "AI Write", icon: Zap },
  { slug: "generate-article", path: "content-machine", category: "AI Write", icon: FileText },
  { slug: "programmatic", path: "content-machine", category: "AI Write", icon: Code2 },

  // --- PDF TOOLS ---
  { slug: "add-images", path: "pdf", category: "Pdf Tools", icon: Image },
  { slug: "add-pages", path: "pdf", category: "Pdf Tools", icon: FileUp },
  { slug: "add-text", path: "pdf", category: "Pdf Tools", icon: Type },
  { slug: "annotate", path: "pdf", category: "Pdf Tools", icon: PenLine },
  { slug: "create", path: "pdf", category: "Pdf Tools", icon: FilePlusIcon },
  { slug: "crop", path: "pdf", category: "Pdf Tools", icon: Scissors },
  { slug: "delete", path: "pdf", category: "Pdf Tools", icon: Eraser },
  { slug: "extract-img", path: "pdf", category: "Pdf Tools", icon: Image },
  { slug: "extract-text", path: "pdf", category: "Pdf Tools", icon: FileText },
  { slug: "from-azw3", path: "pdf", category: "Pdf Tools", icon: Book },
  { slug: "from-eps", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "from-epub", path: "pdf", category: "Pdf Tools", icon: Book },
  { slug: "from-gif", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "from-heic", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "from-jpg", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "from-mobi", path: "pdf", category: "Pdf Tools", icon: Book },
  { slug: "from-msg", path: "pdf", category: "Pdf Tools", icon: Mail },
  { slug: "from-png", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "from-ppt", path: "pdf", category: "Pdf Tools", icon: FileVideo },
  { slug: "from-tiff", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "from-url", path: "pdf", category: "Pdf Tools", icon: Globe },
  { slug: "from-webp", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "from-word", path: "pdf", category: "Pdf Tools", icon: FileText },
  { slug: "protect", path: "pdf", category: "Pdf Tools", icon: FileLock2 },
  { slug: "rearrange", path: "pdf", category: "Pdf Tools", icon: List },
  { slug: "remove-watermark", path: "pdf", category: "Pdf Tools", icon: Eraser },
  { slug: "rotate", path: "pdf", category: "Pdf Tools", icon: RotateCw },
  { slug: "sign", path: "pdf", category: "Pdf Tools", icon: Signature },
  { slug: "split", path: "pdf", category: "Pdf Tools", icon: Scissors },
  { slug: "summarizer", path: "pdf", category: "Pdf Tools", icon: BookOpen },
  { slug: "to-azw3", path: "pdf", category: "Pdf Tools", icon: Book },
  { slug: "to-csv", path: "pdf", category: "Pdf Tools", icon: FileSpreadsheet },
  { slug: "to-epub", path: "pdf", category: "Pdf Tools", icon: Book },
  { slug: "to-jpg", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "to-mobi", path: "pdf", category: "Pdf Tools", icon: Book },
  { slug: "to-png", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "to-ppt", path: "pdf", category: "Pdf Tools", icon: FileVideo },
  { slug: "to-text", path: "pdf", category: "Pdf Tools", icon: Type },
  { slug: "to-tiff", path: "pdf", category: "Pdf Tools", icon: FileImage },
  { slug: "to-word", path: "pdf", category: "Pdf Tools", icon: FileText },
  { slug: "to-xlsx", path: "pdf", category: "Pdf Tools", icon: FileSpreadsheet },
  { slug: "translate", path: "pdf", category: "Pdf Tools", icon: Languages },
  { slug: "unlock", path: "pdf", category: "Pdf Tools", icon: FileKey2 },
  { slug: "watermark", path: "pdf", category: "Pdf Tools", icon: StampIcon },

  // --- VIDEO TOOLS ---
  { slug: "aac-to-flac", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "aac-to-m4r", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "aac-to-mp3", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "aac-to-mp4", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "aac-to-wav", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "add-subtitles", path: "video", category: "Video Tools", icon: Subtitles },
  { slug: "audio-to-text", path: "video", category: "Video Tools", icon: Type },
  { slug: "avi-to-gif", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "avi-to-mkv", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "avi-to-mov", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "avi-to-mp3", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "avi-to-mp4", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "compress-avi", path: "video", category: "Video Tools", icon: Shrink },
  { slug: "compress-mkv", path: "video", category: "Video Tools", icon: Shrink },
  { slug: "compress-mov", path: "video", category: "Video Tools", icon: Shrink },
  { slug: "extract-audio", path: "video", category: "Video Tools", icon: Music },
  { slug: "gif-to-mov", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "gif-to-webm", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "m4a-to-mp3", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "m4a-to-mp4", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "m4a-to-wav", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "mkv-to-avi", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mkv-to-gif", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mkv-to-mov", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mkv-to-mp3", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "mkv-to-mp4", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mov-to-avi", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mov-to-gif", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mov-to-mp3", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "mov-to-mp4", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mov-to-wav", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "mp4-to-avi", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mp4-to-gif", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mp4-to-mov", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mp4-to-mp3", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "mp4-to-ogg", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "mp4-to-wav", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "mp4-to-webm", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "mute", path: "video", category: "Video Tools", icon: VolumeX },
  { slug: "ogg-to-mp3", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "ogg-to-wav", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "resize", path: "video", category: "Video Tools", icon: Scaling },
  { slug: "summarize-podcast", path: "video", category: "Video Tools", icon: Mic },
  { slug: "to-gif", path: "video", category: "Video Tools", icon: Video },
  { slug: "to-text", path: "video", category: "Video Tools", icon: Type },
  { slug: "to-webp", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "transcribe-podcast", path: "video", category: "Video Tools", icon: Mic },
  { slug: "webm-to-mov", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "webm-to-mp3", path: "video", category: "Video Tools", icon: FileAudio },
  { slug: "webm-to-mp4", path: "video", category: "Video Tools", icon: FileVideo },
  { slug: "youtube-to-text", path: "video", category: "Video Tools", icon: Type },
  { slug: "youtube-transcript", path: "video", category: "Video Tools", icon: FileText },

  // --- CONVERTER TOOLS ---
  { slug: "aac", path: "converters", category: "Converter Tools", icon: FileAudio },
  { slug: "avi", path: "converters", category: "Converter Tools", icon: FileVideo },
  { slug: "azw3", path: "converters", category: "Converter Tools", icon: Book },
  { slug: "csv", path: "converters", category: "Converter Tools", icon: FileSpreadsheet },
  { slug: "eps", path: "converters", category: "Converter Tools", icon: FileImage },
  { slug: "epub", path: "converters", category: "Converter Tools", icon: Book },
  { slug: "gif", path: "converters", category: "Converter Tools", icon: FileImage },
  { slug: "heic", path: "converters", category: "Converter Tools", icon: FileImage },
  { slug: "jpg", path: "converters", category: "Converter Tools", icon: FileImage },
  { slug: "m4a", path: "converters", category: "Converter Tools", icon: FileAudio },
  { slug: "mkv", path: "converters", category: "Converter Tools", icon: FileVideo },
  { slug: "mobi", path: "converters", category: "Converter Tools", icon: Book },
  { slug: "mov", path: "converters", category: "Converter Tools", icon: FileVideo },
  { slug: "mp4", path: "converters", category: "Converter Tools", icon: FileVideo },
  { slug: "ogg", path: "converters", category: "Converter Tools", icon: FileAudio },
  { slug: "pdf", path: "converters", category: "Converter Tools", icon: FileText },
  { slug: "png", path: "converters", category: "Converter Tools", icon: FileImage },
  { slug: "psd", path: "converters", category: "Converter Tools", icon: FileImage },
  { slug: "svg", path: "converters", category: "Converter Tools", icon: FileCode },
  { slug: "tiff", path: "converters", category: "Converter Tools", icon: FileImage },
  { slug: "url", path: "converters", category: "Converter Tools", icon: Globe },
  { slug: "vsd", path: "converters", category: "Converter Tools", icon: FileText },
  { slug: "vsdx", path: "converters", category: "Converter Tools", icon: FileText },
  { slug: "webm", path: "converters", category: "Converter Tools", icon: FileVideo },
  { slug: "webp", path: "converters", category: "Converter Tools", icon: FileImage },
  { slug: "xls", path: "converters", category: "Converter Tools", icon: FileSpreadsheet },
  { slug: "xml", path: "converters", category: "Converter Tools", icon: FileCode },
  { slug: "azw3-to-epub", path: "converter", category: "Converter Tools", icon: Book },
  { slug: "azw3-to-mobi", path: "converter", category: "Converter Tools", icon: Book },
  { slug: "csv-to-excel", path: "converter", category: "Converter Tools", icon: FileSpreadsheet },
  { slug: "csv-to-json", path: "converter", category: "Converter Tools", icon: Code2 },
  { slug: "csv-to-xml", path: "converter", category: "Converter Tools", icon: FileCode },
  { slug: "epub-to-azw3", path: "converter", category: "Converter Tools", icon: Book },
  { slug: "epub-to-mobi", path: "converter", category: "Converter Tools", icon: Book },
  { slug: "excel-to-csv", path: "converter", category: "Converter Tools", icon: FileSpreadsheet },
  { slug: "excel-to-pdf", path: "converter", category: "Converter Tools", icon: FileText },
  { slug: "excel-to-xml", path: "converter", category: "Converter Tools", icon: FileCode },
  { slug: "json-to-xml", path: "converter", category: "Converter Tools", icon: FileCode },
  { slug: "mobi-to-azw3", path: "converter", category: "Converter Tools", icon: Book },
  { slug: "mobi-to-epub", path: "converter", category: "Converter Tools", icon: Book },
  { slug: "split-csv", path: "converter", category: "Converter Tools", icon: Scissors },
  { slug: "split-excel", path: "converter", category: "Converter Tools", icon: Scissors },
  { slug: "xml-to-csv", path: "converter", category: "Converter Tools", icon: FileSpreadsheet },
  { slug: "xml-to-excel", path: "converter", category: "Converter Tools", icon: FileSpreadsheet },
  { slug: "xml-to-json", path: "converter", category: "Converter Tools", icon: Code2 },

  // --- WEB TOOLS ---
  { slug: "detect", path: "web", category: "Web Tools", icon: ShieldCheck },
  { slug: "to-jpg", path: "web", category: "Web Tools", icon: FileImage },
  { slug: "to-png", path: "web", category: "Web Tools", icon: FileImage },
  { slug: "trace", path: "web", category: "Web Tools", icon: Globe },

  // --- OTHER TOOLS ---
  { slug: "lorem-ipsum-generator", path: "other", category: "Other Tools", icon: Type },
  { slug: "meme-maker", path: "other", category: "Other Tools", icon: Image },
  { slug: "qr-code", path: "other", category: "Other Tools", icon: QrCode },
  { slug: "unix-timestamp", path: "other", category: "Other Tools", icon: Timer },
  { slug: "zip", path: "other", category: "Other Tools", icon: Archive },
];

function FilePlusIcon(props: any) {
  return React.createElement(
    'svg',
    {
      ...props,
      xmlns: 'http://www.w3.org/2000/svg',
      width: '24',
      height: '24',
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    React.createElement('path', { d: 'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z' }),
    React.createElement('polyline', { points: '14 2 14 8 20 8' }),
    React.createElement('line', { x1: '12', y1: '18', x2: '12', y2: '12' }),
    React.createElement('line', { x1: '9', y1: '15', x2: '15', y2: '15' })
  );
}

function StampIcon(props: any) {
  return React.createElement(
    'svg',
    {
      ...props,
      xmlns: 'http://www.w3.org/2000/svg',
      width: '24',
      height: '24',
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    React.createElement('path', { d: 'M5 22h14' }),
    React.createElement('path', { d: 'M12 17v-4' }),
    React.createElement('path', { d: 'M12 7c-2.8 0-4 1.2-4 4v2h8v-2c0-2.8-1.2-4-4-4z' }),
    React.createElement('path', { d: 'M12 2a3 3 0 0 0-3 3v2h6V5a3 3 0 0 0-3-3z' })
  );
}

// Convert rawTools to the final Tool[] type
// We sort so priority items come first, then the rest by slug
export const tools: Tool[] = rawTools
  .sort((a, b) => {
    if (a.priority && !b.priority) return -1;
    if (!a.priority && b.priority) return 1;
    return a.slug.localeCompare(b.slug);
  })
  .map((t) => ({
    title: formatTitle(t.slug),
    slug: t.slug,
    description: "",
    href: `https://tinywow.com/${t.path}/${t.slug}`,
    category: t.category,
    icon: t.icon,
  }));
